### ISSUE TITLE
Requirements for adding a provider

### ISSUE THREAD

**Issue by zhouhao3** [ansible-network/network-runner#67]
Hi, We want to add support for fos (Fujitsu switch) in network-runner. 
This is the specific [address](https://galaxy.ansible.com/fujitsu/fos) of fos in ansible-galaxy. 
I would like to ask, besides adding the corresponding code, are there any other requirements?

**Comment by radez** [comment]
Only requirement is that it's supported by Ansible Networking.
As long as there's support in Ansible Networking just add the code in network-runner and add to the documentation the features that are implemented.
